version: "3.8"

services:
  postgres_local:
    image: postgres:15
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  backend_local:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
      args:
        GUNICORN_FLASK: ${GUNICORN_FLASK}
        GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT}
        FLASK_RUN_PORT: ${FLASK_RUN_PORT}
        FLASK_RUN_HOST: ${FLASK_RUN_HOST}
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    environment:
      DB_HOST: ollama-postgres_local-1
      DB_NAME: business
      DB_USER_READONLY: ${DB_USER_READONLY}
      DB_PASSWORD_READONLY: ${DB_PASSWORD_READONLY}
    depends_on:
      - postgres_local
    volumes:
      # Mount the model file from the host into the container
      - ./app/backend/models/deepseek-coder-6.7b-instruct.Q4_K_M.gguf:/app/backend/models/deepseek-coder-6.7b-instruct.Q4_K_M.gguf:ro

volumes:
  pgdata:
