services:
  postgres_local:
    container_name: ${DB_HOST}
    image: postgres:15
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_USER_READONLY: ${DB_USER_READONLY}
      DB_PASSWORD_READONLY: ${DB_PASSWORD_READONLY}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "/docker-entrypoint-initdb.d/init.sh && docker-entrypoint.sh postgres",
      ]

  backend_local:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
      args:
        GUNICORN_FLASK: ${GUNICORN_FLASK}
        GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT}
        FLASK_RUN_PORT: ${FLASK_RUN_PORT}
        FLASK_RUN_HOST: ${FLASK_RUN_HOST}
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER_READONLY: ${DB_USER_READONLY}
      DB_PASSWORD_READONLY: ${DB_PASSWORD_READONLY}
    depends_on:
      - postgres_local
    volumes:
      # Mount the model file from the host into the container
      - ./app/backend/models/deepseek-coder-6.7b-instruct.Q4_K_M.gguf:/app/backend/models/deepseek-coder-6.7b-instruct.Q4_K_M.gguf:ro

volumes:
  pgdata:
